# Generated by Django 2.1.2 on 2018-10-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_publish_date', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('a_title', models.CharField(max_length=100)),
                ('a_content', models.TextField()),
                ('a_author', models.CharField(max_length=20)),
                ('a_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
