# Generated by Django 2.1.2 on 2018-11-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodels',
            name='roles',
            field=models.IntegerField(default=0, verbose_name='用户等级'),
        ),
    ]
