# Generated by Django 2.1.2 on 2018-11-05 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='学科名称')),
                ('days', models.IntegerField(null=True, verbose_name='学习时长')),
                ('amount', models.FloatField(max_length=10, null=True, verbose_name='总金额')),
                ('assurance', models.FloatField(blank=True, max_length=20, null=True, verbose_name='最低就业薪资')),
                ('number', models.IntegerField(null=True, verbose_name='排序')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('creater', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creater', to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updater', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '学科信息',
                'verbose_name_plural': '学科信息',
                'db_table': 'subject',
                'ordering': ['number'],
            },
        ),
    ]
