"""
Django settings for restfulproject project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '45-krspde^)2yvdt%&4nf-uzf__xd@!d1l$3pk8q#t(l5%9m1*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apitest.apps.ApitestConfig',
    'rest_framework',
    'corsheaders'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ORIGIN_ALLOW_ALL = True
ROOT_URLCONF = 'restfulproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'restfulproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME':'apitest',
        'USER':'root',
        'PASSWORD':'123456',
        'HOST':'localhost'
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
#这个键是对接口进行全局配置的。
REST_FRAMEWORK={
    # 配置Authenticate类，作为所有接口的认证类，所有接口发送请求，都要先经过这个类的认证，看是否已经登录。相当于你在每一个接口类中都设置了一个authentication_classes=[Authentication]
    # "DEFAULT_AUTHENTICATION_CLASSES":['utils.base_authenticate.Authentication'],
    # 配置默认使用的权限认证类，如果某一个接口不需要使用这个默认的，可以在自己的类中设置局部的permission_classes=[VIPPermission]，这个局部的就可以覆盖默认的认证类
    # 'DEFAULT_PERMISSION_CLASSES':['utils.base_authenticate.VIPPermission'],
    # 配置自定义的访问控制类
    # 'DEFAULT_THROTTLE_CLASSES':['utils.base_authenticate.IPThrottle'],
    # 使用Throttle内置的访问控制类
    'DEFAULT_THROTTLE_RATES': {
        'IP': '3/m',  # 'IP'就是源码中的scope，'3/m'就是源码中的rate。
        'USER': '10/m'  #'USER'就是源码中的scope，'10/m'就是源码中的rate。
    },
    # 配置默认的版本信息
    'DEFAULT_VERSION': 'v1',  # 如果GET没有传参数，默认使用v1
    'ALLOWED_VERSION': ['v1', 'v2'],  # 对版本号进行检查，检查前端传递的版本号是否支持
    #配置全局页数变量控制
    "DEFAULT_PAGINATION_CLASS": ["rest_framework.pagination.PageNumberPagination"],
    'PAGE_SIZE': 1, #每页返回几条数据
}
