# Generated by Django 2.0.7 on 2018-12-10 08:48

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_sn', models.CharField(default='', help_text='商品唯一货号', max_length=50, verbose_name='商品唯一货号')),
                ('name', models.CharField(help_text='商品名', max_length=100, verbose_name='商品名')),
                ('click_num', models.IntegerField(default=0, help_text='商品点击数', verbose_name='商品点击数')),
                ('sold_num', models.IntegerField(default=0, help_text='商品销售量', verbose_name='商品销售量')),
                ('fav_num', models.IntegerField(default=0, help_text='商品收藏数', verbose_name='商品收藏数')),
                ('goods_num', models.IntegerField(default=0, help_text='商品库存数', verbose_name='商品库存数')),
                ('market_price', models.FloatField(default=0, help_text='商品市场价格', verbose_name='商品市场价格')),
                ('shop_price', models.FloatField(default=0, help_text='商品本店价格', verbose_name='商品本店价格')),
                ('goods_brief', models.TextField(help_text='商品简短描述', max_length=500, verbose_name='商品简短描述')),
                ('goods_desc', DjangoUeditor.models.UEditorField(default='', help_text='商品详情内容', verbose_name='商品详情内容')),
                ('ship_free', models.BooleanField(default=True, help_text='是否承担运费', verbose_name='是否承担运费')),
                ('goods_front_image', models.ImageField(blank=True, help_text='商品封面图', null=True, upload_to='goods/images/', verbose_name='商品封面图')),
                ('is_new', models.BooleanField(default=False, help_text='商品是否新品', verbose_name='商品是否新品')),
                ('is_hot', models.BooleanField(default=False, help_text='商品是否热销', verbose_name='商品是否热销')),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='商品添加时间', verbose_name='商品添加时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='GoodsBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='轮播图图片', upload_to='banner', verbose_name='轮播图图片')),
                ('index', models.IntegerField(default=0, help_text='轮播图播放顺序', verbose_name='轮播图播放顺序')),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='轮播图片添加时间', verbose_name='添加时间')),
                ('goods', models.ForeignKey(help_text='轮播图片所属商品ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '轮播商品',
                'verbose_name_plural': '轮播商品',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名')),
                ('code', models.CharField(default='', help_text='类别编号', max_length=30, verbose_name='类别编号')),
                ('desc', models.TextField(blank=True, default='', help_text='类别描述', null=True, verbose_name='类别描述')),
                ('category_type', models.IntegerField(choices=[(1, '一级类录'), (2, '二级类录'), (3, '三级类录')], help_text='类目级别', verbose_name='类目级别')),
                ('is_tab', models.BooleanField(default=False, help_text='导航分类', verbose_name='导航分类')),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='goods.GoodsCategory', verbose_name='父类目录')),
            ],
            options={
                'verbose_name': '商品类别',
                'verbose_name_plural': '商品类别',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategoryBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='推荐品牌名称', max_length=30, verbose_name='品牌名')),
                ('desc', models.TextField(default='', help_text='推荐品牌描述', verbose_name='推荐品牌描述')),
                ('image', models.ImageField(help_text='推荐品牌图片', upload_to='brands/images')),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='推荐品牌添加时间')),
                ('category', models.ForeignKey(blank=True, help_text='推荐品牌所属类别id', null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='商品类目')),
            ],
            options={
                'verbose_name': '品牌名',
                'verbose_name_plural': '品牌名',
            },
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='轮播图图片', null=True, upload_to='', verbose_name='图片')),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='轮播图添加时间', verbose_name='添加时间')),
                ('goods', models.ForeignKey(help_text='轮播图所属商品ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(help_text='商品所属类别id', null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='商品类目'),
        ),
    ]
