# Generated by Django 2.1.2 on 2018-11-27 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shengxian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_order_time', models.DateTimeField(auto_now_add=True, verbose_name='生成订单时间')),
                ('order_branch', models.IntegerField(null=True, verbose_name='订单号')),
                ('payment_status', models.CharField(max_length=50, verbose_name='支付状态')),
                ('food_produce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shengxian.FoodProduct', verbose_name='关联商品')),
                ('shop_cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shengxian.ShopCart', verbose_name='关联的购物车')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
    ]
