# Generated by Django 2.1.2 on 2018-10-29 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_name', models.CharField(max_length=100)),
                ('new_content', models.TextField()),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='NewsAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'new_author',
            },
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'new_name',
            },
        ),
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'new_type',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='news_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm.NewsAuthor'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm.NewsTag'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm.NewsType'),
        ),
    ]
