# Generated by Django 2.1.2 on 2018-10-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_url', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'pic',
            },
        ),
    ]
